title: OSHx
email: oshxios@gmail.com
description: 
  This is my blog.
baseurl: ""
url: "https://oshx.github.io"
twitter_username: oshxios
github_username:  oshx

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
